### ISSUE TITLE
PelIllegalFormatException: Unknown format: 0x0

### ISSUE THREAD

**Issue by Commifreak** [pel/pel#183]
We recenty upgraded to PHP 7.4 with PEL 0.9.10. Since then, we have the following error after the first EXIF write:

```
                lsolesen\pel\PelIllegalFormatException: Unknown format: 0x0 in /var/www/dev.deutsche-genbank-obst.de/vendor/lsolesen/pel/src/PelFormat.php:224
Stack trace:
#0 /var/www/dev.deutsche-genbank-obst.de/vendor/lsolesen/pel/src/PelIfd.php(723): lsolesen\pel\PelFormat::getSize()
#1 /var/www/dev.deutsche-genbank-obst.de/vendor/lsolesen/pel/src/PelIfd.php(649): lsolesen\pel\PelIfd->loadSingleValue()
#2 /var/www/dev.deutsche-genbank-obst.de/vendor/lsolesen/pel/src/PelTiff.php(159): lsolesen\pel\PelIfd->load()
#3 /var/www/dev.deutsche-genbank-obst.de/vendor/lsolesen/pel/src/PelExif.php(100): lsolesen\pel\PelTiff->load()
#4 /var/www/dev.deutsche-genbank-obst.de/vendor/lsolesen/pel/src/PelJpeg.php(216): lsolesen\pel\PelExif->load()
#5 /var/www/dev.deutsche-genbank-obst.de/controllers/PassportController.php(426): lsolesen\pel\PelJpeg->load()
```

The first write of exif is successful. The second (open already edited file) does not load anymore.

Downgrading to 0.9.9 works.

**Comment by agaktr** [comment]
anything here anyone?

**Comment by agaktr** [comment]
Found a potential fix or at least a round over the issue. 
pel\src\PelFormat.php

[PelFormat.zip](https://github.com/pel/pel/files/6264657/PelFormat.zip)

**Comment by DeveloperMarius** [comment]
Seems to be related to #174.

**Comment by ovidiul** [comment]
Similar problem with the latest version 0.9.10, I am using the following code to remove GPS data as:

```
<?php

require_once './vendor/autoload.php';

use lsolesen\pel\PelJpeg;
use lsolesen\pel\PelIfd;

$filename = 'test.jpg';

$jpeg = new PelJpeg( $filename );
$exif = $jpeg->getExif();
$tiff = $exif->getTiff();
$ifd0 = $tiff->getIfd();

// removing GPS data by adding a new empty PelIfd::GPS IFD.
$gps = $ifd0->addSubIfd( new PelIfd( PelIfd::GPS ) );

// saving the new file.
$jpeg->saveFile( 'new-' . $filename );
```

but opening the `new-test.jpg` generated file shows this error:

```
lsolesen\pel\PelIllegalFormatException: Unknown format: 0x0 in /.../vendor/lsolesen/pel/src/PelFormat.php on line 224
```

**Comment by ViktorasssIT** [comment]
Did you found a fix?

**Comment by ViktorasssIT** [comment]
> Similar problem with the latest version 0.9.10, I am using the following code to remove GPS data as:
> 
> ```
> <?php
> 
> require_once './vendor/autoload.php';
> 
> use lsolesen\pel\PelJpeg;
> use lsolesen\pel\PelIfd;
> 
> $filename = 'test.jpg';
> 
> $jpeg = new PelJpeg( $filename );
> $exif = $jpeg->getExif();
> $tiff = $exif->getTiff();
> $ifd0 = $tiff->getIfd();
> 
> // removing GPS data by adding a new empty PelIfd::GPS IFD.
> $gps = $ifd0->addSubIfd( new PelIfd( PelIfd::GPS ) );
> 
> // saving the new file.
> $jpeg->saveFile( 'new-' . $filename );
> ```
> 
> but opening the `new-test.jpg` generated file shows this error:
> 
> ```
> lsolesen\pel\PelIllegalFormatException: Unknown format: 0x0 in /.../vendor/lsolesen/pel/src/PelFormat.php on line 224
> ```

Did you found a fix to this issue? Having the same problem now.

**Comment by Rar9** [comment]
Any hope to get this fixed any time soon?

**Comment by ViktorasssIT** [comment]
> Any hope to get this fixed any time soon?

Downgraded to 0.9.9 and it fixed the issue.

**Comment by Rar9** [comment]
> > Any hope to get this fixed any time soon?
> 
> Downgraded to 0.9.9 and it fixed the issue.

Not possible as its used by drupal fdm

**Comment by weberhofer** [comment]
Please test with latest release 0.9.12

**Comment by StavoveiC** [comment]
I tested with release 0.9.12 but the issue is still present. Then I tried the fix from https://github.com/pel/pel/issues/183#issuecomment-814087415 and it works.
